# Generated by Django 3.0 on 2019-12-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mail_send',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_uuid',
        ),
    ]
