# Generated by Django 3.0 on 2020-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200113_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
