# Generated by Django 3.0 on 2020-01-13 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timetable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('number_of_credits', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(default=0, max_length=50)),
                ('classroom', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(timetable.models.DayOfWeek['MO'], 'Monday'), (timetable.models.DayOfWeek['TU'], 'Tuesday'), (timetable.models.DayOfWeek['WE'], 'Wednesday'), (timetable.models.DayOfWeek['TR'], 'Thursday'), (timetable.models.DayOfWeek['FR'], 'Friday'), (timetable.models.DayOfWeek['SA'], 'Saturday'), (timetable.models.DayOfWeek['SU'], 'Sunday')], max_length=5, unique=True)),
                ('periods', models.ManyToManyField(to='timetable.Period')),
            ],
        ),
    ]
